# Generated by Django 2.2.6 on 2020-05-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendError',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='newsletter',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
