# Generated by Django 2.2.6 on 2020-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='baseproduct_ptr',
        ),
        migrations.DeleteModel(
            name='MetaProduct',
        ),
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='a', max_length=128, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='short_url',
            field=models.CharField(default='a', max_length=64, verbose_name='short url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.CharField(default='a', max_length=256, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BaseProduct',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
