# Generated by Django 2.2.6 on 2020-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery_time',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='panel_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_capacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='refresh_rate',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
