# Generated by Django 2.2.6 on 2020-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200505_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery_time',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='in hours', max_digits=3, null=True),
        ),
    ]
