# Generated by Django 2.2.6 on 2020-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200504_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='depth',
            field=models.PositiveSmallIntegerField(help_text='in millimeters'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='guarantee',
            field=models.PositiveSmallIntegerField(help_text='in years'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='height',
            field=models.PositiveSmallIntegerField(help_text='in millimeters'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='manufacturing_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='manufacturing name'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='in kilograms', max_digits=3),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='width',
            field=models.PositiveSmallIntegerField(help_text='in millimeters'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery_time',
            field=models.DecimalField(decimal_places=1, help_text='in hours', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(help_text='primary color', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='panel_type',
            field=models.CharField(help_text='for example TN or IPS', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_capacity',
            field=models.PositiveSmallIntegerField(help_text='in gigabytes', null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='refresh_rate',
            field=models.PositiveSmallIntegerField(help_text='in hertz', null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.PositiveSmallIntegerField(help_text='in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, help_text='in inches', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_size',
            field=models.PositiveSmallIntegerField(help_text='in gigabytes', null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(help_text='for example HDD or SSD', max_length=128, null=True),
        ),
    ]
