# Generated by Django 2.2.6 on 2020-05-02 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200502_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='placement',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
