# Generated by Django 2.2.6 on 2020-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200504_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='depth',
            field=models.PositiveSmallIntegerField(help_text='in millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='height',
            field=models.PositiveSmallIntegerField(help_text='in millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='in kilograms', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='width',
            field=models.PositiveSmallIntegerField(help_text='in millimeters', null=True),
        ),
    ]
