# Generated by Django 2.2.6 on 2020-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200505_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='refresh_rate',
            field=models.DecimalField(decimal_places=1, help_text='in hertz', max_digits=3, null=True),
        ),
    ]
