# Generated by Django 2.2.6 on 2020-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200502_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
