# Generated by Django 2.2.6 on 2020-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200505_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='height',
            field=models.DecimalField(decimal_places=1, help_text='in millimeters', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='refresh_rate',
            field=models.PositiveSmallIntegerField(help_text='in hertz', null=True),
        ),
    ]
