# Generated by Django 2.2.6 on 2020-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200504_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='guarantee',
            field=models.PositiveSmallIntegerField(help_text='in years', null=True),
        ),
    ]
