# Generated by Django 2.2.6 on 2020-05-02 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_image_is_duplicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_duplicate',
        ),
        migrations.AlterField(
            model_name='image',
            name='placement',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
