# Generated by Django 2.2.6 on 2020-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200504_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='panel_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(choices=[('HDD', 'hdd'), ('SSD', 'ssd')], max_length=128, null=True),
        ),
    ]
